spring.application.name=Lab_emt

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.profiles.active=dev
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=864000000
jwt.header=Authorization
jwt.token-prefix=Bearer
JWT_SECRET_KEY=47a9c1ed3beff7bdb82646599e90bc7ed8e0b20306717b03bc5495bc6efd9bf3